<?php
declare(strict_types=1);

/**
 * Enterprise Database Seeder
 * Run via CLI: php app/cli/seed.php
 */

require_once dirname(__DIR__, 2) . '/vendor/autoload.php';

use App\Storage\JsonStorageEngine;

$engine = JsonStorageEngine::getInstance();

echo "Memulakan proses seeding data Helpdesk ICTBKP...\n";

// 1. SEED USERS
$users = [
    [
        'id' => 'USR-ADMIN-01',
        'name' => 'Mohd Azhar bin Mansor',
        'email' => 'admin@bkp.gov.my',
        'password' => password_hash('password123', PASSWORD_DEFAULT),
        'role' => 'ADMIN',
        'unit' => 'ICT_BKP',
        'position' => 'Penolong Pegawai Teknologi Maklumat F29 / Pentadbir ICT',
        'phone' => '012-3456789',
        'is_active' => true,
        'created_at' => date('c'),
    ],
    [
        'id' => 'USR-KU-PENTADBIRAN',
        'name' => 'Datin Hajah Rohana binti Hashim',
        'email' => 'ketua.pentadbiran@bkp.gov.my',
        'password' => password_hash('password123', PASSWORD_DEFAULT),
        'role' => 'KETUA_UNIT',
        'unit' => 'PENTADBIRAN',
        'position' => 'Ketua Penolong Setiausaha (Unit Pentadbiran)',
        'phone' => '013-9876543',
        'is_active' => true,
        'created_at' => date('c'),
    ],
    [
        'id' => 'USR-KU-ASET',
        'name' => 'Encik Kamaruddin bin Salleh',
        'email' => 'ketua.aset@bkp.gov.my',
        'password' => password_hash('password123', PASSWORD_DEFAULT),
        'role' => 'KETUA_UNIT',
        'unit' => 'BANGUNAN_ASET',
        'position' => 'Ketua Penolong Setiausaha (Unit Bangunan & Aset)',
        'phone' => '019-1122334',
        'is_active' => true,
        'created_at' => date('c'),
    ],
    [
        'id' => 'USR-KU-KESELAMATAN',
        'name' => 'Mejar (B) Hairul Nizam bin Ramli',
        'email' => 'ketua.keselamatan@bkp.gov.my',
        'password' => password_hash('password123', PASSWORD_DEFAULT),
        'role' => 'KETUA_UNIT',
        'unit' => 'KESELAMATAN_BENCANA',
        'position' => 'Ketua Penolong Setiausaha (Unit Keselamatan & Bencana)',
        'phone' => '012-9988776',
        'is_active' => true,
        'created_at' => date('c'),
    ],
    [
        'id' => 'USR-KU-KEWANGAN',
        'name' => 'Puan Norashikin binti Othman',
        'email' => 'ketua.kewangan@bkp.gov.my',
        'password' => password_hash('password123', PASSWORD_DEFAULT),
        'role' => 'KETUA_UNIT',
        'unit' => 'KEWANGAN',
        'position' => 'Akauntan / Ketua Penolong Setiausaha (Unit Kewangan)',
        'phone' => '017-3344556',
        'is_active' => true,
        'created_at' => date('c'),
    ],
    [
        'id' => 'USR-KU-ISTIADAT',
        'name' => 'Tuan Haji Shamsul Anuar bin Idris',
        'email' => 'ketua.istiadat@bkp.gov.my',
        'password' => password_hash('password123', PASSWORD_DEFAULT),
        'role' => 'KETUA_UNIT',
        'unit' => 'ISTIADAT_PROTOKOL',
        'position' => 'Pegawai Protokol Negeri / Ketua Unit Istiadat',
        'phone' => '019-5566778',
        'is_active' => true,
        'created_at' => date('c'),
    ],
    [
        'id' => 'USR-KU-DASAR',
        'name' => 'Puan Zaidah binti Ariffin',
        'email' => 'ketua.dasar@bkp.gov.my',
        'password' => password_hash('password123', PASSWORD_DEFAULT),
        'role' => 'KETUA_UNIT',
        'unit' => 'DASAR_PEROLEHAN',
        'position' => 'Ketua Penolong Setiausaha (Unit Dasar & Perolehan)',
        'phone' => '018-7788990',
        'is_active' => true,
        'created_at' => date('c'),
    ],
    [
        'id' => 'USR-STAF-TSUK',
        'name' => 'Siti Nur Aisyah binti Zakaria',
        'email' => 'staf.tsuk@bkp.gov.my',
        'password' => password_hash('password123', PASSWORD_DEFAULT),
        'role' => 'STAF',
        'unit' => 'TSUK',
        'position' => 'Setiausaha Pejabat TSUK (Pengurusan)',
        'phone' => '011-22334455',
        'is_active' => true,
        'created_at' => date('c'),
    ],
    [
        'id' => 'USR-STAF-PENTADBIRAN',
        'name' => 'Ahmad Faiz bin Khairuddin',
        'email' => 'staf.pentadbiran@bkp.gov.my',
        'password' => password_hash('password123', PASSWORD_DEFAULT),
        'role' => 'STAF',
        'unit' => 'PENTADBIRAN',
        'position' => 'Penolong Pegawai Tadbir N29',
        'phone' => '014-5566112',
        'is_active' => true,
        'created_at' => date('c'),
    ],
    [
        'id' => 'USR-STAF-KEWANGAN',
        'name' => 'Nurul Huda binti Sulaiman',
        'email' => 'staf.kewangan@bkp.gov.my',
        'password' => password_hash('password123', PASSWORD_DEFAULT),
        'role' => 'STAF',
        'unit' => 'KEWANGAN',
        'position' => 'Penolong Akauntan W29',
        'phone' => '016-8877665',
        'is_active' => true,
        'created_at' => date('c'),
    ],
];

$engine->write('users', $users);
echo "Berjaya seed " . count($users) . " pengguna.\n";

// 2. SEED ASSETS
$assets = [
    [
        'id' => 'AST-IPH-01',
        'asset_code' => 'BKP/ICT/IPH/2026/01',
        'name' => 'Apple iPhone 15 Pro 256GB (Hitam Titanium)',
        'type' => 'IPHONE',
        'brand' => 'Apple',
        'model' => 'iPhone 15 Pro',
        'serial_no' => 'IPH15P-MY-88901',
        'status' => 'TERSEDIA',
        'condition' => 'BAIK',
        'notes' => 'Termasuk kabel USB-C, power adapter 20W & casing keselamatan',
        'created_at' => date('c'),
    ],
    [
        'id' => 'AST-IPH-02',
        'asset_code' => 'BKP/ICT/IPH/2026/02',
        'name' => 'Apple iPhone 14 Pro 128GB (Deep Purple)',
        'type' => 'IPHONE',
        'brand' => 'Apple',
        'model' => 'iPhone 14 Pro',
        'serial_no' => 'IPH14P-MY-77612',
        'status' => 'TERSEDIA',
        'condition' => 'BAIK',
        'notes' => 'Termasuk kabel Lightning & power adapter',
        'created_at' => date('c'),
    ],
    [
        'id' => 'AST-CAM-01',
        'asset_code' => 'BKP/ICT/CAM/2026/01',
        'name' => 'Kamera DSLR Canon EOS R6 Mark II + Lensa 24-105mm',
        'type' => 'KAMERA_DSLR',
        'brand' => 'Canon',
        'model' => 'EOS R6 Mark II Kit',
        'serial_no' => 'CN-R6M2-99014',
        'status' => 'TERSEDIA',
        'condition' => 'BAIK',
        'notes' => 'Termasuk 2x bateri LP-E6NH, charger, SanDisk Extreme Pro 128GB & beg kamera',
        'created_at' => date('c'),
    ],
    [
        'id' => 'AST-CAM-02',
        'asset_code' => 'BKP/ICT/CAM/2026/02',
        'name' => 'Kamera Sony Alpha A7 IV + Lensa FE 24-70mm GM',
        'type' => 'KAMERA_DSLR',
        'brand' => 'Sony',
        'model' => 'ILCE-7M4',
        'serial_no' => 'SN-A7M4-33418',
        'status' => 'TERSEDIA',
        'condition' => 'BAIK',
        'notes' => 'Termasuk SD Card 128GB, dual charger & strap bahu',
        'created_at' => date('c'),
    ],
    [
        'id' => 'AST-MIC-01',
        'asset_code' => 'BKP/ICT/MIC/2026/01',
        'name' => 'Sistem Mikrofon Wireless RODE Wireless PRO (2 Transmitters + Receiver)',
        'type' => 'MIKROFON_AUDIO',
        'brand' => 'RODE',
        'model' => 'Wireless PRO Dual-Channel',
        'serial_no' => 'RD-WPRO-11452',
        'status' => 'TERSEDIA',
        'condition' => 'BAIK',
        'notes' => 'Termasuk charging case, 2x Lavalier II, kabel 3.5mm & USB-C lightning adaptors',
        'created_at' => date('c'),
    ],
    [
        'id' => 'AST-MIC-02',
        'asset_code' => 'BKP/ICT/MIC/2026/02',
        'name' => 'Set Mikrofon Dual Wireless Shure BLX288/PG58',
        'type' => 'MIKROFON_AUDIO',
        'brand' => 'Shure',
        'model' => 'BLX288/PG58',
        'serial_no' => 'SH-BLX288-66710',
        'status' => 'TERSEDIA',
        'condition' => 'BAIK',
        'notes' => '2x Wireless handheld microphone & receiver station lengkap kabel XLR',
        'created_at' => date('c'),
    ],
    [
        'id' => 'AST-LAP-01',
        'asset_code' => 'BKP/ICT/LAP/2026/01',
        'name' => 'Laptop Dell Latitude 5440 (Intel Core i7-1365U, 16GB RAM, 512GB SSD)',
        'type' => 'KOMPUTER_RIBA',
        'brand' => 'Dell',
        'model' => 'Latitude 5440',
        'serial_no' => 'DL-5440-ABC12',
        'status' => 'TERSEDIA',
        'condition' => 'BAIK',
        'notes' => 'Siap dipasang Windows 11 Enterprise, MS Office 365, Zoom & Teams',
        'created_at' => date('c'),
    ],
    [
        'id' => 'AST-LAP-02',
        'asset_code' => 'BKP/ICT/LAP/2026/02',
        'name' => 'Laptop Lenovo ThinkPad T14s Gen 4 (AMD Ryzen 7 PRO, 16GB, 512GB)',
        'type' => 'KOMPUTER_RIBA',
        'brand' => 'Lenovo',
        'model' => 'ThinkPad T14s G4',
        'serial_no' => 'LN-T14S-88934',
        'status' => 'TERSEDIA',
        'condition' => 'BAIK',
        'notes' => 'Termasuk kabel kuasa 65W USB-C & beg galas rasmi',
        'created_at' => date('c'),
    ],
    [
        'id' => 'AST-LAP-03',
        'asset_code' => 'BKP/ICT/LAP/2026/03',
        'name' => 'Apple MacBook Pro 14 (Cip Apple M3 Pro, 18GB Unified Memory, 512GB)',
        'type' => 'KOMPUTER_RIBA',
        'brand' => 'Apple',
        'model' => 'MacBook Pro 14 M3 Pro',
        'serial_no' => 'AP-MBP14-99812',
        'status' => 'TERSEDIA',
        'condition' => 'BAIK',
        'notes' => 'Dikhaskan untuk editing video pantas & pembentangan kenamaan',
        'created_at' => date('c'),
    ],
    [
        'id' => 'AST-PRJ-01',
        'asset_code' => 'BKP/ICT/PRJ/2026/01',
        'name' => 'Projektor Pintar Epson EB-2250U 5,000 Lumens Full HD',
        'type' => 'PROJEKTOR_SKRIN',
        'brand' => 'Epson',
        'model' => 'EB-2250U',
        'serial_no' => 'EP-2250-44519',
        'status' => 'TERSEDIA',
        'condition' => 'BAIK',
        'notes' => 'Termasuk kabel HDMI 10 meter, kabel kuasa dan alat kawalan jauh',
        'created_at' => date('c'),
    ],
    [
        'id' => 'AST-PRS-01',
        'asset_code' => 'BKP/ICT/PRS/2026/01',
        'name' => 'Presenter Penunjuk Laser Logitech Spotlight Wireless',
        'type' => 'PENUNJUK_LASER',
        'brand' => 'Logitech',
        'model' => 'Spotlight Advanced',
        'serial_no' => 'LG-SPOT-11002',
        'status' => 'TERSEDIA',
        'condition' => 'BAIK',
        'notes' => 'Termasuk USB Dongle receiver & kabel pengecas Type-C',
        'created_at' => date('c'),
    ],
];

$engine->write('assets', $assets);
echo "Berjaya seed " . count($assets) . " aset inventori.\n";

// 3. SEED TICKETS SAMPLE
$today = date('Y-m-d');
$tomorrow = date('Y-m-d', strtotime('+1 day'));
$nextWeek = date('Y-m-d', strtotime('+7 days'));

$sampleTickets = [
    [
        'id' => 'TCK-DEMO-001',
        'reference_no' => 'ICTBKP/2026/08/0001',
        'category' => 'PEMINJAMAN_ASET',
        'title' => 'Peminjaman iPhone & Kamera DSLR untuk Majlis Perhimpunan Bulanan BKP',
        'purpose' => 'Rakaman media siaran langsung dan dokumentasi rasmi warga BKP bersama Pengurusan Tertinggi',
        'user_id' => 'USR-STAF-PENTADBIRAN',
        'applicant_name' => 'Ahmad Faiz bin Khairuddin',
        'applicant_email' => 'staf.pentadbiran@bkp.gov.my',
        'applicant_phone' => '014-5566112',
        'applicant_position' => 'Penolong Pegawai Tadbir N29',
        'unit' => 'PENTADBIRAN',
        'unit_name' => 'Unit Pentadbiran',
        'status' => 'DILULUSKAN',
        'start_date' => $tomorrow,
        'end_date' => $tomorrow,
        'start_time' => '08:00',
        'end_time' => '13:00',
        'location' => 'Dewan Serbaguna Kompleks Kerajaan',
        'requested_equipment_types' => ['IPHONE', 'KAMERA_DSLR'],
        'assigned_asset_ids' => ['AST-IPH-01', 'AST-CAM-01'],
        'meeting_type' => null,
        'meeting_platform' => null,
        'meeting_link' => null,
        'meeting_passcode' => null,
        'vip_attendees' => 'YBhg. TSUK Pengurusan & Ketua-ketua Unit BKP',
        'media_scope' => null,
        'event_agenda' => '',
        'unit_approval' => [
            'status' => 'APPROVED',
            'approved_by' => 'USR-KU-PENTADBIRAN',
            'approver_name' => 'Datin Hajah Rohana binti Hashim',
            'notes' => 'Disokong. Majlis rasmi bulanan.',
            'action_at' => date('c', strtotime('-2 hours')),
        ],
        'ict_approval' => [
            'status' => 'APPROVED',
            'approved_by' => 'USR-ADMIN-01',
            'approver_name' => 'Mohd Azhar bin Mansor',
            'assigned_technician_id' => 'USR-ADMIN-01',
            'assigned_technician_name' => 'Mohd Azhar bin Mansor',
            'notes' => 'Diluluskan. Peralatan telah sedia untuk diambil di Kaunter ICT.',
            'action_at' => date('c', strtotime('-1 hour')),
        ],
        'remarks' => 'Sila ambil 30 minit sebelum acara.',
        'created_at' => date('c', strtotime('-3 hours')),
        'updated_at' => date('c', strtotime('-1 hour')),
    ],
    [
        'id' => 'TCK-DEMO-002',
        'reference_no' => 'ICTBKP/2026/08/0002',
        'category' => 'SOKONGAN_MESYUARAT',
        'title' => 'Sokongan Teknikal & Hos Mesyuarat Penyelarasan Bajet Tahunan BKP',
        'purpose' => 'Mesyuarat Hibrid bersama Perbendaharaan Negeri & Pejabat Daerah',
        'user_id' => 'USR-STAF-KEWANGAN',
        'applicant_name' => 'Nurul Huda binti Sulaiman',
        'applicant_email' => 'staf.kewangan@bkp.gov.my',
        'applicant_phone' => '016-8877665',
        'applicant_position' => 'Penolong Akauntan W29',
        'unit' => 'KEWANGAN',
        'unit_name' => 'Unit Kewangan',
        'status' => 'MENUNGGU_KELULUSAN_ICT',
        'start_date' => $nextWeek,
        'end_date' => $nextWeek,
        'start_time' => '09:30',
        'end_time' => '12:30',
        'location' => 'Bilik Mesyuarat Utama BKP (Aras 3)',
        'requested_equipment_types' => ['KOMPUTER_RIBA', 'MIKROFON_AUDIO'],
        'assigned_asset_ids' => [],
        'meeting_type' => 'HYBRID_ONLINE_DAN_FIZIKAL',
        'meeting_platform' => 'ZOOM',
        'meeting_link' => 'https://zoom.us/j/9876543210',
        'meeting_passcode' => 'BKP2026',
        'vip_attendees' => 'Ketua Penolong Pegawai Kewangan Negeri',
        'media_scope' => null,
        'event_agenda' => 'Pembentangan Agihan Bajet Emolumen dan Operasi 2027',
        'unit_approval' => [
            'status' => 'APPROVED',
            'approved_by' => 'USR-KU-KEWANGAN',
            'approver_name' => 'Puan Norashikin binti Othman',
            'notes' => 'Disokong. Memerlukan bantuan standby juruteknik.',
            'action_at' => date('c', strtotime('-30 minutes')),
        ],
        'ict_approval' => [
            'status' => 'PENDING',
            'approved_by' => null,
            'approver_name' => null,
            'assigned_technician_id' => null,
            'assigned_technician_name' => null,
            'notes' => null,
            'action_at' => null,
        ],
        'remarks' => '',
        'created_at' => date('c', strtotime('-1 hour')),
        'updated_at' => date('c', strtotime('-30 minutes')),
    ],
    [
        'id' => 'TCK-DEMO-003',
        'reference_no' => 'ICTBKP/2026/08/0003',
        'category' => 'MEDIA_JURUKAMERA',
        'title' => 'Khidmat Jurukamera & Juruvideo Kunjungan Hormat Delegasi Antarabangsa',
        'purpose' => 'Dokumentasi foto & video penuh kunjungan delegasi luar negara ke Pejabat TSUK Pengurusan',
        'user_id' => 'USR-STAF-TSUK',
        'applicant_name' => 'Siti Nur Aisyah binti Zakaria',
        'applicant_email' => 'staf.tsuk@bkp.gov.my',
        'applicant_phone' => '011-22334455',
        'applicant_position' => 'Setiausaha Pejabat TSUK (Pengurusan)',
        'unit' => 'TSUK',
        'unit_name' => 'Pejabat TSUK Pengurusan',
        'status' => 'MENUNGGU_SOKONGAN_UNIT',
        'start_date' => date('Y-m-d', strtotime('+3 days')),
        'end_date' => date('Y-m-d', strtotime('+3 days')),
        'start_time' => '10:00',
        'end_time' => '12:00',
        'location' => 'Bilik Mesyuarat Pejabat TSUK Pengurusan (Aras 4)',
        'requested_equipment_types' => [],
        'assigned_asset_ids' => [],
        'meeting_type' => null,
        'meeting_platform' => null,
        'meeting_link' => null,
        'meeting_passcode' => null,
        'vip_attendees' => 'YBhg. Timbalan Setiausaha Kerajaan & Duta Besar',
        'media_scope' => 'FOTO_DAN_VIDEO',
        'event_agenda' => 'Sesi Menandatangani Buku Pelawat, Perbincangan Meja Bulat & Sesi Fotografi Rasmi',
        'unit_approval' => [
            'status' => 'PENDING',
            'approved_by' => null,
            'approver_name' => null,
            'notes' => null,
            'action_at' => null,
        ],
        'ict_approval' => [
            'status' => 'PENDING',
            'approved_by' => null,
            'approver_name' => null,
            'assigned_technician_id' => null,
            'assigned_technician_name' => null,
            'notes' => null,
            'action_at' => null,
        ],
        'remarks' => 'Gambar dan video hi-res diperlukan untuk siaran media sosial rasmi SUK.',
        'created_at' => date('c', strtotime('-15 minutes')),
        'updated_at' => date('c', strtotime('-15 minutes')),
    ],
];

$engine->write('tickets', $sampleTickets);
$engine->write('counters', ['tickets_2026_08' => 3]);
echo "Berjaya seed " . count($sampleTickets) . " tiket permohonan contoh.\n";

// 4. SEED AUDIT LOGS
$auditLogs = [
    [
        'id' => 'AUD-001',
        'action' => 'SYSTEM_INIT',
        'description' => 'Sistem Helpdesk ICTBKP dimulakan dan dikonfigurasi.',
        'ticket_id' => null,
        'user_id' => 'USR-ADMIN-01',
        'user_name' => 'Mohd Azhar bin Mansor',
        'user_email' => 'admin@bkp.gov.my',
        'user_role' => 'ADMIN',
        'user_unit' => 'ICT_BKP',
        'ip_address' => '127.0.0.1',
        'user_agent' => 'Seeder Script',
        'metadata' => ['env' => 'production'],
        'created_at' => date('c'),
    ]
];

$engine->write('audit_logs', $auditLogs);
echo "Berjaya seed log audit sistem.\n";

echo "Proses seeding SELESAI dengan jaya!\n";
